version: '3'
services:
  office-prod:
    container_name: office-prod
    image: nginx:1.12
    networks:
     - application_prod_network
    volumes:
      - ../dist:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"

networks:
  application_prod_network:
    driver: bridge
    name: application_prod_network